*====================================
* permisos.prg
* Generado automáticamente
*====================================

PUBLIC PERM_ACTUALIZAR_STOCK
PERM_ACTUALIZAR_STOCK = "ACTUALIZAR_STOCK"

PUBLIC PERM_ANULAR_FACTURA
PERM_ANULAR_FACTURA = "ANULAR_FACTURA"

PUBLIC PERM_ASIGNAR_PERMISOS
PERM_ASIGNAR_PERMISOS = "ASIGNAR_PERMISOS"

PUBLIC PERM_CREAR_FACTURA
PERM_CREAR_FACTURA = "CREAR_FACTURA"

PUBLIC PERM_CREAR_ROLES
PERM_CREAR_ROLES = "CREAR_ROLES"

PUBLIC PERM_INFORME_EJECUTIVO
PERM_INFORME_EJECUTIVO = "INFORME_EJECUTIVO"

PUBLIC PERM_INFORME_GENERAL
PERM_INFORME_GENERAL = "INFORME_GENERAL"

PUBLIC PERM_MODIFICAR_PRECIO
PERM_MODIFICAR_PRECIO = "MODIFICAR_PRECIO"

PUBLIC PERM_MODIFICAR_STOCK
PERM_MODIFICAR_STOCK = "MODIFICAR_STOCK"

PUBLIC PERM_VENTAS
PERM_VENTAS = "VENTAS"

PUBLIC PERM_VER_COSTOS
PERM_VER_COSTOS = "VER_COSTOS"

